#ifndef _ADDR_H_
#define _ADDR_H_

//shared mem
#define INPUT_DATA_ADDR				0
#define LAYERS_AMOUNT_ADDR			1000
#define LAYERS_NEURONS_AMOUNT_ADDR	2000
#define LAYERS_OFFSET_ADDR			3000
#define NEURONS_OFFSET_ADDR			4000
#define ACTIVATION_DATA_ADDR		5000

//local mem
#define FIRST_LOCAL_MEM_ADDR		6000
#define SECOND_LOCAL_MEM_ADDR		7000
#define THIRD_LOCAL_MEM_ADDR		8000
#define FOURTH_LOCAL_MEM_ADDR		9000
#define FIFTH_LOCAL_MEM_ADDR		10000

#endif
